{% set name = "arctic" %}
{% set version = "1.80.2" %}
{% set sha256 = "cd5d9e63cb17229986a93331135fdff978d48703a8dcdedb9e1fdab109fd8ead" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools
    - setuptools-git
    - six
    - numpy
    - pip
  run:
    - python >=3.4
    - decorator
    - pandas
    - pymongo >=3.6.0
    - python-dateutil
    - pytz
    - tzlocal
    - lz4
    - enum-compat
    - mockextras

test:
  imports:
    - arctic

about:
  home: https://github.com/manahl/arctic
  license: LGPL-2.1-only
  license_family: GPL
  license_file: LICENSE
  summary: High performance datastore for time series and tick data
  description: |
    Arctic is a high performance datastore for numeric data. It supports
    Pandas, numpy arrays and pickled objects out-of-the-box, with pluggable
    support for other data types and optional versioning.

    Arctic can query millions of rows per second per client, achieves ~10x
    compression on network bandwidth, ~10x compression on disk, and scales
    to hundreds of millions of rows per second per MongoDB instance.

    Arctic has been under active development at Man AHL since 2012.
  doc_url: https://arctic.readthedocs.io/en/latest/
  dev_url: https://github.com/manahl/arctic

extra:
  recipe-maintainers:
    - birnbaum
    - mathiaseitz
    - trendelkampschroer
